### ISSUE TITLE
How does this work ?

### ISSUE THREAD

**Issue by niahoo** [phpBBSEO/usu#123]
Hi, 

I cannot activate the class configuration module in the ACP, it make the whole phpbb SEO page crash.
My only way to activate url rewriting is to do the following in the customise `inject` function:

```PHP
$this->core->seo_opt['url_rewrite'] = true;
```

How do you enable pretty URLs in the generated HTML ?

Thank you.

**Comment by niahoo** [comment]
I tried the extension on a fresh new forum and the page with settings shows as expected. So I think my forum is f***ed up ... Sorry for the inconvenience !

**Comment by Galixte** [comment]
https://github.com/phpBBSEO/usu/issues/122#issuecomment-302260742

**Comment by niahoo** [comment]
I know but it kind of work. Do you know any replacement ? I have a huge forum to migrate to 3.1, we currently do not want to migrate to another forum engine because it is too much work.

**Comment by Galixte** [comment]
Why to continue with this old script? You don’t need the URL rewriting anymore.

phpBB 3.1.x will not recieve security patches after december 2017, phpBB 3.2.x is the good choice (or 3.3.x but it’s not released yet).

So, apply your migration to phpBB 3.2.x, the only thing to do: you have to keep the URL rewriting rules from your .htaccess file from your phpBB 3.0.x board and transfer/copy these in the new .htaccess file from phpBB 3.2.x.

With this way, your old urls rewritten will continue to work and the new urls will be like the native URL from phpBB 3.2.x. You won’t have any decrease from SEO on Google, the major point to have on your board it’s an original content renewed from to to time, not gadget. ;)

Moreover, migrate to HTTPS in the next months it’s an important point to consider towards about SEO.

**Comment by niahoo** [comment]
Well, if the forum outputs native URLs, all current internal links will change. Do you think that Google will not care ?

New content is not a problem, sure, but old content is 1st google result for many researchs, I feel it's too risky. By the way, this extension does not seem to be that complicated to fix if I need it.

Or I misunderstood your message and you are saying that 3.2 has native URL rewriting capabilities ? I'll check.

Thank you

**Comment by Galixte** [comment]
“Well, if the forum outputs native URLs, all current internal links will change. Do you think that Google will not care ?

…old content is 1st google result for many researchs,” Absolutely not, with this way the old content will continue to work with the old URLs (rewritten of course!).

“Or I misunderstood your message and you are saying that 3.2 has native URL rewriting capabilities ? I'll check.” no, i didn’t say that.

You can read this topic (in FRENCH) the Adminstrator of phpBB-fr.com has tested this way and it’s work. He explains by an example of how to do in .htaccess files: http://forums.phpbb-fr.com/support-utilisation-phpbb32/sujet209364-15.html#p1647573. ;)

**Comment by niahoo** [comment]
I'm french :)

Ok so we may drop pretty URLs if they are not so important for SEO.
