### ISSUE TITLE
Access to undeclared static property: phpbbseo\usu\core::

### ISSUE THREAD

**Issue by fhemberger** [phpBBSEO/usu#81]
When I uncomment any of the settings in `customise.php`, (e.g. `core::$seo_ext['topic']`), I get this php error message (running phpBB 3.1.2, current master-branch of usu):

`Fatal error: Access to undeclared static property: phpbbseo\usu\core::$seo_ext in /usr/htdocs/rpg.dev/ext/phpbbseo/usu/customise.php on line 75`

**Comment by dcz** [comment]
Apparently we need to update the comments. Just use $this-> instead of core::$ and it will work as expected.

**Comment by fhemberger** [comment]
LGTM :+1:
