### ISSUE TITLE
CSS hover effect breaks on prosilver based style

### ISSUE THREAD

**Issue by forkless** [phpBBSEO/usu#93]
When using the PBTech style the hover effect for the post buttons/icons stops working when USU is enabled.

Eg. http://dev2.forkless.com/announcements/welcome-to-phpbb3-t1.html

The quote button on the post should not be visible until mouse over.

**Comment by fhemberger** [comment]
I think I found the bug here: https://github.com/phpBBSEO/usu/blob/master/styles/all/template/phpbb_seo.js#L69

```js
if (phpbb_seo.ext_classes) {
	var extclass = new RegExp("(^|\s)(" + seo_ext_classes + ")(\s|$)");
}
```

should be

```js
if (phpbb_seo.ext_classes) {
	var extclass = new RegExp("(^|\s)(" + phpbb_seo.ext_classes + ")(\s|$)");
}
```

**Comment by forkless** [comment]
Doesn't seem to eleviate the issue for me, unfortunately.

**Comment by fhemberger** [comment]
Bummer, thought the script was manipulating CSS classes, but your issue still exists with JS disabled.

**Comment by forkless** [comment]
Thanks for trying never the less ^^
